#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "react-tailwind-view"
main = "main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]
scope = ""

[assets]
directory = "./view-build"
binding = "ASSETS"

[deco]
workspace = ""
bindings = []
enable_workflows = true
local = false

[[migrations]]
tag = "v1"
new_classes = [ "Workflow" ]

[durable_objects]
[[durable_objects.bindings]]
name = "DECO_CHAT_WORKFLOW_DO"
class_name = "Workflow"